version: '3'

services:
  cerberus.identityserver:
    image: cerberusidentityserver
    build:
      context: .
      dockerfile: Cerberus.IdentityServer/Dockerfile

  hracles:
    image: hracles
    build:
      context: .
      dockerfile: Héracles/Dockerfile

